---
- hosts: linux
  tasks:
  -  name: Create user (egoad/RubberDuck!)
     user: 
      name: egoad
      password: RubberDuck!     #wont work
    become: yes
  - name: Create second user (ddvevito/GetShorty!)
    become: yes
    user:
      name: ddvito
      password: "{{ 'GetShorty!' | password_hash('sha512') }}"
  - name: Create third user (webAdmin/encrypted password)
    become: yes
    user:
      name: webAdmin
      password: '$6$sR3GN7U9w64EfL.j$1Pu4E06KXboDQc9jywt6dnis4Goo/L.SU3OKE9JwO19QB8UN1NwTdWVz5h82PROFxpAP8eMrplE2rivJvmDuE.'

- hosts: db 
  tasks:
  - name: Install MariaDB
    become: yes
    apt: 
      name: mariadb-server
      state: present
  - name: Enable MariaDB (set to autostart)
    become: yes
    service:
      name: mariadb
      enabled: yes
  - name: Start MariaDB
    become: yes
    service:
      name: mariadb
      state: started


- hosts: web  
  tasks:
  - name: Install Apache
    become: yes
    apt: name=apache2 state=present
  - name: Set Apache to run
    become: yes
    service: name=apache2 state=started enabled=yes

  - name: Confiugure firewall to open http
    become: yes
    ufw: 
      rule: allow
      port: 80
      proto: tcp
    notify:
      - restart-firewall
  handlers:
    - name: restart-firewall
      become: yes
      ufw:
        state: reloaded

